### ISSUE TITLE
i have python 3.7 can u adjust file to work please

### ISSUE THREAD

**Issue by waelnoaman** [chuanenlin/shutterscrape#12]
![issue](https://user-images.githubusercontent.com/33648398/61437636-43189480-a946-11e9-94e9-7cd0e830cb20.JPG)

C:\Users\adel\Desktop\shutterscrape-master>python shutterscrape.py
Traceback (most recent call last):
  File "shutterscrape.py", line 12, in <module>
    from urllib import urlretrieve
ImportError: cannot import name 'urlretrieve' from 'urllib' (C:\Users\adel\AppDa
ta\Local\Programs\Python\Python37-32\lib\urllib\__init__.py)

**Comment by chuanenlin** [comment]
It looks like you are using Python 3 which uses request instead of Python 2 which uses urlretrieve. To make it work for Python 3, you may comment out the section for Python 2 and uncomment the section for Python 3 (see code comments).

**Comment by waelnoaman** [comment]
i remove comments from Python 3 

but still have issue 

![999999999](https://user-images.githubusercontent.com/33648398/61441210-d1dcdf80-a94d-11e9-91e7-8e58d8ad7c4c.JPG)

**Comment by chuanenlin** [comment]
Try commenting out the line "For python3" and make sure that indention is correct for the rest of the code section (e.g. aligned to the left).

**Comment by waelnoaman** [comment]
Still have syntax error

![code](https://user-images.githubusercontent.com/33648398/61442473-5d577000-a950-11e9-8041-f2809f6a8ece.JPG)
![222222222222222222222222](https://user-images.githubusercontent.com/33648398/61442474-5df00680-a950-11e9-9959-b27683429998.JPG)

**Comment by chuanenlin** [comment]
Try indenting the rest of the code block one block to the left. You may read [this](https://www.programiz.com/python-programming/statement-indentation-comments) to learn more about Python indention rules.

**Comment by waelnoaman** [comment]
Solved , thanks alot
