### ISSUE TITLE
Great Tool

### ISSUE THREAD

**Issue by waelnoaman** [chuanenlin/shutterscrape#13]
Dear Chuanenlin

thanks for your best tool , but its fetch low dpi from shutter stock as we need to fetches full dpi images
for example : 
![beautiful-business-lady-looking-camera-260nw-593494403](https://user-images.githubusercontent.com/33648398/61448683-06f02e80-a95c-11e9-9a77-efdc5f2205d4.jpg)

i saw another tool ( It fetches full dpi images from Shutterstock and Gettyimages by an api endpoint. )
https://github.com/aman29271/shutterstock-and-getty-random-image

try to improve your tool

**Comment by chuanenlin** [comment]
This repository was written for scraping images from Shutterstock for training an object detection classifier and works by fetching the preview images - hence the low resolution. Fetching full resolution images from Shutterstock would also be considered stealing from its creators.
