### ISSUE TITLE
Use requests, not selenium

### ISSUE THREAD

**Issue by xtream1101** [chuanenlin/shutterscrape#2]
You do not need to use selenium at all and just use requests, this will make your scripts run way faster. 
Here is an example I created to show off how for gettyimages: https://gist.github.com/xtream1101/090aab1e00e245284a15af3f7cfaab05

Also for shutterstock you can hit this url where I searched for `house`
 https://www.shutterstock.com/sstk/api/footage/search?language=en&q=house&page%5Bsize%5D=50&page%5Boffset%5D=0&recordActivity=true&fields%5Bvideos%5D=description%2Cpreview_video_urls%2Cpreview_image_url%2Cduration%2Csizes%2Cuploaded_date

Which will yield nice json data of all the results.

You can also thread the downloads to be even faster.

**Comment by chuanenlin** [comment]
Great! Do you also happen to find a work-around for fetching videos from Shutterstock? Feel free to commit also if you happen to find a way to add on multi-threading. Thank you for your contributions!
